# using case of pandas

- Data cleaning 
- Data Analysis
- Data Transfromation
- Data visualization
- Data Aggregation
- File Handling
- Data Filtering & Selection
- Time Series Analysis

# Pandas Seris

### A Seris ia a One-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

# Crating Seris:

### There are multiple ways to create a pandas seris:

In [1]:
import pandas as pd
import numpy as np

In [2]:
my_list = [10,20,30]
arr = np.array([40,50,60])
dic = {'a':70,'b':80,'c':90}
label = ['g','h','i']

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index=["d","e","f"])

d    10
e    20
f    30
dtype: int64

In [5]:
pd.Series(arr,index=label)

g    40
h    50
i    60
dtype: int64

In [6]:
pd.Series(dic)

a    70
b    80
c    90
dtype: int64

# Data Frames:

### when you combile multiple seris to create data framaes.

## creating a DataFrame

In [7]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

df = pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age      City
a    Alice   25  New York
b      Bob   30    London
c  Charlie   35     Paris

In [8]:
data_list = [
    ['Alice',25,'New York'],
    ['Bob',30,'London'],
    ['Charlie',35,'Paris']
]
df2= pd.DataFrame(data_list)
df2

         0   1         2
0    Alice  25  New York
1      Bob  30    London
2  Charlie  35     Paris

In [9]:
columns = ["name","age","city"]
df2= pd.DataFrame(data_list,columns = columns)
df2

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

## Selection and Indexing of Columns

In [10]:
df['Name']

a      Alice
b        Bob
c    Charlie
Name: Name, dtype: str

In [11]:
df[['Name','City']]

      Name      City
a    Alice  New York
b      Bob    London
c  Charlie     Paris

## Creating a new Column

In [12]:
df2['std'] = [8,9,10]
df2

      name  age      city  std
0    Alice   25  New York    8
1      Bob   30    London    9
2  Charlie   35     Paris   10

## Removing Columns

In [13]:
df2.drop('std',axis=1) # default axis 0 and 0 axis work left to right          # main data ma kai no delete tay

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [14]:
df2.drop('std',axis=1,inplace=True) # main data ma delete tay

In [15]:
df2

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [16]:
df2.drop(['city','age'],axis=1) # multiple column drop

      name
0    Alice
1      Bob
2  Charlie

In [17]:
df2.drop(0,axis=0)

      name  age    city
1      Bob   30  London
2  Charlie   35   Paris

## Selection Rows

In [18]:
df

      Name  Age      City
a    Alice   25  New York
b      Bob   30    London
c  Charlie   35     Paris

In [19]:
df.loc['a'] # loc means location

Name       Alice
Age           25
City    New York
Name: a, dtype: object

In [20]:
df.loc[['a','c']]

      Name  Age      City
a    Alice   25  New York
c  Charlie   35     Paris

In [21]:
df.iloc[1] # index location

Name       Bob
Age         30
City    London
Name: b, dtype: object

## Selection Subset of Rows and Columns

In [22]:
df.loc[['a','c']][['Age','City']]

   Age      City
a   25  New York
c   35     Paris

In [23]:
df.loc[['b','a']][['Name','Age']]

    Name  Age
b    Bob   30
a  Alice   25

## Conditional Selection

In [24]:
df2

      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

#### I only want to see those people whose age is above 30:

In [25]:
df2[df2["age"] > 30]

      name  age   city
2  Charlie   35  Paris

#### I only want poeple whose age is above 30 and their city must be paris:

In [26]:
df2[(df2["age"] > 30) & (df2["city"] == "Paris")]

      name  age   city
2  Charlie   35  Paris

# Missing Data:

##  Finding Missing Data

In [27]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [25, np.nan, 30, 22],
    'Salary': [50000, 60000, None, 52000]
}

df = pd.DataFrame(data)

df

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
3      NaN  22.0  52000.0

In [28]:
df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3   True  False   False

In [29]:
df.isna().sum()

Name      1
Age       1
Salary    1
dtype: int64

In [30]:
df.isna().any()

Name      True
Age       True
Salary    True
dtype: bool

##  Removing Missing Data

In [31]:
df # Removing data work by base on Rows

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
3      NaN  22.0  52000.0

In [32]:
df.dropna()

    Name   Age   Salary
0  Alice  25.0  50000.0

In [33]:
df.dropna(thresh=3)

    Name   Age   Salary
0  Alice  25.0  50000.0

## Filling the Missing Data

In [34]:
df

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  30.0      NaN
3      NaN  22.0  52000.0

In [35]:
df.fillna(0)

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob   0.0  60000.0
2  Charlie  30.0      0.0
3        0  22.0  52000.0

In [36]:
# missing values for difderent values of each column
# fill and Selection Row wise

In [37]:
values = {"Age":30,"Name":"Avinash","Salary":50000}
df.fillna(value=values)

      Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0  60000.0
2  Charlie  30.0  50000.0
3  Avinash  22.0  52000.0

# Merging Joining and Concatination

## Merging 2 dataframes

In [38]:
data1 = {
    "Emp_ID": [101, 102, 103, 104],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 22, 28]
}
df1 = pd.DataFrame(data1)


data2 = {
    "Emp_ID": [101, 102, 103, 105],
    "Department": ["HR", "Engineering", "Marketing", "Sales"],
    "City": ["New York", "San Francisco", "London", "Chicago"]
}
df2 = pd.DataFrame(data2)

df1

   Emp_ID     Name  Age
0     101    Alice   25
1     102      Bob   30
2     103  Charlie   22
3     104    David   28

In [39]:
df2

   Emp_ID   Department           City
0     101           HR       New York
1     102  Engineering  San Francisco
2     103    Marketing         London
3     105        Sales        Chicago

In [40]:
pd.merge(df1,df2) # by default hoe perfrom to inner opeartion

   Emp_ID     Name  Age   Department           City
0     101    Alice   25           HR       New York
1     102      Bob   30  Engineering  San Francisco
2     103  Charlie   22    Marketing         London

In [41]:
pd.merge(df1,df2,on="Emp_ID",how='outer')

   Emp_ID     Name   Age   Department           City
0     101    Alice  25.0           HR       New York
1     102      Bob  30.0  Engineering  San Francisco
2     103  Charlie  22.0    Marketing         London
3     104    David  28.0          NaN            NaN
4     105      NaN   NaN        Sales        Chicago

In [42]:
pd.merge(df1,df2,on="Emp_ID",how='left')

   Emp_ID     Name  Age   Department           City
0     101    Alice   25           HR       New York
1     102      Bob   30  Engineering  San Francisco
2     103  Charlie   22    Marketing         London
3     104    David   28          NaN            NaN

In [43]:
pd.merge(df1,df2,on="Emp_ID",how='right')

   Emp_ID     Name   Age   Department           City
0     101    Alice  25.0           HR       New York
1     102      Bob  30.0  Engineering  San Francisco
2     103  Charlie  22.0    Marketing         London
3     105      NaN   NaN        Sales        Chicago

## Concatination of 2 dataframes

In [44]:
df1 = pd.DataFrame({
    'Store_ID': [101, 102, 103],
    'Product': ['Apple', 'Banana', 'Orange'],
    'Sales': [250, 180, 310]
})

df1

   Store_ID Product  Sales
0       101   Apple    250
1       102  Banana    180
2       103  Orange    310

In [45]:
df2 = pd.DataFrame({
    'Store_ID': [104, 105, 106],
    'Product': ['Apple', 'Mango', 'Banana'],
    'Sales': [210, 150, 190]
})

df2

   Store_ID Product  Sales
0       104   Apple    210
1       105   Mango    150
2       106  Banana    190

In [46]:
pd.concat([df1,df2])

   Store_ID Product  Sales
0       101   Apple    250
1       102  Banana    180
2       103  Orange    310
0       104   Apple    210
1       105   Mango    150
2       106  Banana    190

In [47]:
pd.concat([df2,df1]) # base on column

   Store_ID Product  Sales
0       104   Apple    210
1       105   Mango    150
2       106  Banana    190
0       101   Apple    250
1       102  Banana    180
2       103  Orange    310

In [48]:
pd.concat([df1,df2],axis=1) # base on rows

   Store_ID Product  Sales  Store_ID Product  Sales
0       101   Apple    250       104   Apple    210
1       102  Banana    180       105   Mango    150
2       103  Orange    310       106  Banana    190

## joining of 2 dataframes

In [49]:
emp1 = {
    'Employee_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Dept_ID': [1, 2, 1, 4]  
}
df_1 = pd.DataFrame(emp1)


dep = {
    'Dept_ID': [1, 2, 3], 
    'Dept_Name': ['HR', 'Engineering', 'Marketing']
}
df_2 = pd.DataFrame(dep)

df_2

   Dept_ID    Dept_Name
0        1           HR
1        2  Engineering
2        3    Marketing

In [50]:
df_1

   Employee_ID     Name  Dept_ID
0          101    Alice        1
1          102      Bob        2
2          103  Charlie        1
3          104    David        4

In [51]:
df_1.join(df_2,lsuffix='_emp', rsuffix='_dept')

   Employee_ID     Name  Dept_ID_emp  Dept_ID_dept    Dept_Name
0          101    Alice            1           1.0           HR
1          102      Bob            2           2.0  Engineering
2          103  Charlie            1           3.0    Marketing
3          104    David            4           NaN          NaN

### Differnce between merge and join 
• pd.merge() (SQL-style):

	• Best used when you want to match specific columns from two different tables (e.g., matching Employee_ID to Employee_ID).
	• Allows you to specify left and right columns or indices explicitly using left_on and right_on.

• df.join() (Index-style):

	• Best used when both of your datasets already share a clean, identical index (like a Date or an ID set as the index).
	• Saves keystrokes when combining a list of DataFrames that align by their row labels.

# Group By Aggregation

In [ ]:
# Group by dos'n create dataframe create object

In [52]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [53]:
# Group by Category and calculate the sum of Sales
cat = df.groupby("Category")["Sales"].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [54]:
# Group by Store and calculate the sum of Sales
cat = df.groupby("Store")["Sales"].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [55]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(["Store","Category"])["Sales"].sum()
cat

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

## Aggregation

In [57]:
df["Sales"].mean()
df["Sales"].min()
df["Sales"].sum()

np.int64(1500)

In [59]:
df["Sales"].agg(['mean','sum','min','max'])

mean     187.5
sum     1500.0
min      100.0
max      300.0
Name: Sales, dtype: float64

# PivotTable and Cross Tabs

In [60]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    139     82   John  January      Q1
1  2023-01-02       B   West    363     62   Mary  January      Q1
2  2023-01-03       C  North    723     12    Bob  January      Q1
3  2023-01-04       D  South    131     51  Alice  January      Q1
4  2023-01-05       A   East    572     50   John  January      Q1
5  2023-01-06       B   West    836     64   Mary  January      Q1
6  2023-01-07       C  North    561     46    Bob  January      Q1
7  2023-01-08       D  South    141     84  Alice  January      Q1
8  2023-01-09       A   East    449     68   John  January      Q1
9  2023-01-10       B   West    885     75   Mary  January      Q1
10 2023-01-11       C  North    621     57    Bob  January      Q1
11 2023-01-12       D  South    591     41  Alice  January      Q1
12 2023-01-13       A   East    582     48   John  January      Q1
13 2023-01-14       B   West    524     77   Mary  January      Q1
14 2023-01-15       C  North    550     68    Bob  January      Q1
15 2023-01-16       D  South    731     14  Alice  January      Q1
16 2023-01-17       A   East    157     13   John  January      Q1
17 2023-01-18       B   West    353     22   Mary  January      Q1
18 2023-01-19       C  North    265     31    Bob  January      Q1
19 2023-01-20       D  South    389     11  Alice  January      Q1

In [ ]:
# pivottable use case hit map creation

In [61]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product")

Product      A      B      C      D
Region
East     379.8    NaN    NaN    NaN
North      NaN    NaN  544.0    NaN
South      NaN    NaN    NaN  396.6
West       NaN  592.2    NaN    NaN

In [62]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product",aggfunc='sum')

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     1899.0     NaN     NaN     NaN  261.0    NaN    NaN    NaN
North       NaN     NaN  2720.0     NaN    NaN    NaN  214.0    NaN
South       NaN     NaN     NaN  1983.0    NaN    NaN    NaN  201.0
West        NaN  2961.0     NaN     NaN    NaN  300.0    NaN    NaN

## Cross tab

In [64]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [ ]:
# agg fuction use in pivot table and count in cross tab

# Opeartion

### DataFrames Basic Operations

In [65]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [66]:
df1.shape

(5, 3)

In [67]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [69]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [70]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A'] + 10 # Boradcasting

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

### DataFrames Applying Functions

In [72]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
def square(x):
    return x ** 2

In [78]:
df1['E'] = df1["B"].apply("square")

In [79]:
df1

   A     B    C        E
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [82]:
df1['D'] = df1["E"].apply(lambda X: X ** 2 )

In [81]:
df1

   A     B    C        E        D
0  1   100  100    10000    10000
1  2   400  200   160000   160000
2  3   900  300   810000   810000
3  4  1600  400  2560000  2560000
4  5  2500  500  6250000  6250000